server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: 127.0.0.1
  server:
    enableSelfPreservation: false

spring:
  application:
    name: cloud-registry
